name: Deploy Express App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Setup project structure
        run: |
          mkdir -p build/public
          cp -r public/* build/public/ || true
          cp server.js build/
          cp package.json build/
          cp package-lock.json build/ || true
      
      - name: Create Procfile for hosting platforms
        run: |
          echo "web: node server.js" > build/Procfile
        
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
        
      - name: Set Heroku remote
        run: heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
        
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "build"
