name: Deploy static content to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add build step here if needed (e.g., npm run build)
      # - name: Build
      #   run: |
      #     npm install
      #     npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./ # Or your build output directory (e.g., './dist')

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          branch: gh-pages  # Correct parameter name
          commit-message: 'Deploy static content to GitHub Pages'  # Optional
